name: Fetch and Merge Crypto Data

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC
  workflow_dispatch:

jobs:
  fetch-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv with Python 3.12
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.12'
          enable-cache: true

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install -e .

      - name: Setup Kaggle API
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

      - name: Debug Kaggle Auth
        run: uv run kaggle datasets list -s btc
        
      - name: Run data processing script
        run: uv run python kaggle_bitcoin/kaggle_update_bitcoin.py

      - name: Upload data to Kaggle
        run: |
          utc_date=$(date -u +"%Y-%m-%d")
          uv run kaggle datasets version -m "Automated daily update for $utc_date" -p ./upload --dir-mode zip

